# Generated by Django 4.1b1 on 2022-07-17 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autopark', '0002_alter_autoparkmodel_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autoparkmodel',
            options={'ordering': ['id']},
        ),
    ]
